config/routes.rb
IdeaMapr::Application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  devise_for :admins, only: [:sessions, :passwords]
  
  resources :users, path: 'profiles'

  get '/public_info/double_bundle' => 'public_info#double_bundle'

  resources :respondents, only: [] do
    collection do
      get :reset
    end
  end
      
  resources :individual_answers, only: [:create, :update]
  resources :ideas
  resources :survey_questions
  resources :question_details, only: [:index, :create]

  resources :surveys do
    collection do
      post '/update', action: 'update'
      get '/public_show/:public_link', action: 'public_show', as: 'public_show'
    end
    member do
      get :report
    end
  end
  
  post '/ajax_api' => 'ajax#multiplex'
  get '/ajax_api' => 'ajax#multiplex'
  
  root to: 'ideas#index'

  # Adds RailsAdmin
  mount RailsAdmin::Engine => '/rails_admin', as: 'rails_admin'

  # Need a catch all to redirect to the errors controller, for catching 404s as an exception
  match "*path", to: "errors#catch_404", via: [:get, :post]
end

app/models/idea.rb
class Idea < ActiveRecord::Base
  include IdeasHelper
  
  def self.viewbox_list
    unless Struct.const_defined? 'IdeaVbStruct'
      Struct.new('IdeaVbStruct', :partial_name, :title, :box_key, :shown, :expected_length, :help_text) do
        def initialize(*args)
          super
          self.shown = true
          self.expected_length ||= -1 
        end
      end
    end
    
    [Struct::IdeaVbStruct.new('title', 'Idea Title', 'idea-title', true, 1, 'Add a short title'),
     Struct::IdeaVbStruct.new('source', 'Source', 'idea-source', true, 10, ''),     
     Struct::IdeaVbStruct.new('location', 'Location', 'idea-location', true, -1, 'Enter an optional location'),
     Struct::IdeaVbStruct.new('description', 'Idea Intro', 'idea-description', true, 1, 'Describe your idea'),
     Struct::IdeaVbStruct.new('attachments', 'Attachments', 'idea-attachments', true, 1, 'Upload attachments')
    ]
  end
  
  def surveys
    Survey.where('id in (?)',
                 IdeaAssignment.where('idea_id = ? and groupable_type = ?', self.id, 'Survey').pluck(:groupable_id))
  end
  def survey_questions
    SurveyQuestion.where('id in (?)',
                 IdeaAssignment.where('idea_id = ? and groupable_type = ?', self.id, 'SurveyQuestion').pluck(:groupable_id))
  end
  
  def attachments_oldest_first
    download_files.order('download_files.created_at asc')
  end

  def card_image    
    attachments_oldest_first.all.select do |attach|
      is_image? attach.downloadable_content_type      
    end.first
  end

  def download_files_hash
    # Construct a hash suitable for participant app
    card_image_url = ''
    url_list = attachments_oldest_first.all.map do |attach|
      if is_image? attach.downloadable_content_type
        card_image_url = attach.downloadable.url
      end
      {url: attach.downloadable.url, filename: attach.downloadable_file_name}
    end

    {card_image_url: card_image_url, attachment_urls: url_list}
  end
  
  validates :title, length: {minimum: 1}
  validates :description, length: {minimum: 1}
  has_many :idea_assignments, dependent: :destroy
  has_many :download_files

  before_save :set_default_source

  private
  def set_default_source
    source.present? or (self.source = 'admin')
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_menubar_variables
  before_action :authenticate_admin!
  before_action :params_check

  helper IdeasHelper
  
  def new
    @level2_menu = :create_idea
  end
    
  def index
    @all_ideas = Idea.order(created_at: :desc).map do |i|
      base_info = {id: i.id, title: i.title, description: i.description}
      base_info.merge!({attachments: i.download_files_hash})
      base_info
    end
    
    if params[:for_survey_question]
      selected_idea_assignments =
        if params[:for_survey_question].to_i == 0
          # new survey questions have no ideas
          []
        else
          @question.idea_assignments.pluck(:idea_id, :ordering, :budget)
        end
      assignments_rev_index =
        selected_idea_assignments.inject({}) do |memo, rec_data|
        memo[rec_data[0]] = {ordering: rec_data[1], budget: rec_data[2]}
        memo
      end
      @all_ideas.each do |idea_rec|
        i = idea_rec[:id]
        if (already_assigned = assignments_rev_index.keys.include?(i))
          idea_rec.merge!({component_rank: assignments_rev_index[i][:ordering],
                           cart_amount: assignments_rev_index[i][:budget]})
        end
        idea_rec.merge!({is_assigned: already_assigned})
      end
    end

    render json_payload
  end

  def edit
    @level2_menu = :create_idea
    if @idea.download_files.count > 0
      @attachments_oldest_first = @idea.attachments_oldest_first
    end
  end

  def show
    @idea = Idea.find_by_id params[:id]
    @idea ? (request.xhr? ? render(json: @idea) : (render 'show')) : (redirect_to page_404)
  end
  
  def update
    attrs = params[:idea].permit :title, :description
    @idea.attributes= attrs

    if @idea.valid?
      @idea.save
      if params[:idea][:attachment]
        df = DownloadFile.new downloadable: params[:idea][:attachment]
        df.idea = @idea
        df.save
      end
      
      redirect_to ideas_path
    else
      flash.now[:alert] = t(:resource_creation_failure, resource_name: 'Idea')
      render (params[:action] == 'create' ? :new : :edit)
    end
  end
  alias :create :update
  
  private
  def json_payload
    if request.xhr?
      {json: @all_ideas}
    else
      'index'
    end
  end
  
  def set_menubar_variables
    @navbar_active_section = :ideas
  end

  def params_check
    status = true
    case params[:action].to_sym
    when :new
      @idea = Idea.new
      # For use in view helpers
      @form_object = @idea      
    when :show, :edit
      status &= (params[:id].present? and @idea=Idea.find_by_id(params[:id]))
      # For use in view helpers
      @form_object = @idea
    when :index
      # XHR request for new SQ will send SQ id = 0
      status &= (params[:for_survey_question].nil? || params[:for_survey_question].to_i == 0 ||
                 (@question = SurveyQuestion.find_by_id(params[:for_survey_question])))
    when :create, :update
      status &= (params[:id].nil? || (@idea = Idea.find_by_id(params[:id])))
      status &= !params[:idea].nil?
      if @idea.nil?
        @idea = Idea.new
      end
    end

    if !status
      redirect_to page_404
    end

    return status
  end
end

app/helpers/ideas_helper.rb
module IdeasHelper
  def is_image?(type)
    type = type.downcase
    type=~ /image.png/ || type =~ /image.jpeg/ || type =~ /image.gif/ || type =~ /image.jpg/ ||
      type =~ /image.tif/ || type =~ /image.bmp/
  end
end

app/views/ideas/_attachments.html.haml
.row
  - found_image = false
  - @attachments_oldest_first&.each do |a|
    .col-xs-12.attachment-desc{'data-attachment-id' => a.id}
      .x-box
        X
      = link_to a.downloadable_file_name, a.downloadable.url, target: '_blank', rel: 'noopener noreferrer'
      - if is_image?(a.downloadable_content_type)
        - if !found_image
          - found_image = true
          (Card image)
.row      
  .col-xs-offset-3.col-xs-6.text-center
    .attachment-div
      = file_field_tag 'idea[attachment]', id: 'attachment-button'
      #fake-link
        .fake-link-text
          Upload Attachment
        .current-attachment
          No upload selected

app/views/ideas/_description.html.haml
.relative-container
  = text_area_tag 'idea[description]', @idea.description, class: 'form-control validated-box', 'data-expected-length' => vb.expected_length
  = label_tag 'idea[description]', t('prompts.idea.description'), class: 'placeholder-label'

app/views/ideas/_location.html.haml
.relative-container
  = text_field_tag 'idea[location]', @idea.location, class: 'form-control validated-box', autofocus: true, 'data-expected-length' => vb.expected_length
  = label_tag 'idea[location]', t('prompts.idea.location'), class: 'placeholder-label'

app/views/ideas/_source.html.haml
.relative-container
  .idea-source
    = @idea.source

app/views/ideas/_title.html.haml
.relative-container
  = text_field_tag 'idea[title]', @idea.title, class: 'form-control validated-box', autofocus: true, 'data-expected-length' => vb.expected_length
  = label_tag 'idea[title]', t('prompts.idea.title'), class: 'placeholder-label'

app/views/ideas/_type__1_admin_template.html.haml
%script#type--1-public-template{type: 'text/template'}
  .row.ranking.idea-row.component-row
    .idea.col-xs-12.question-data{'data-object-id' => '<%- id %>'.html_safe, 'data-object-type' => 'idea'}
      .x-box
        X
      = render partial: 'idea_card', locals: {remove_bottom: true}

app/views/ideas/edit.html.haml
= form_tag("/ideas/#{@idea.id}", method: :post, multipart: true) do
  = hidden_field_tag '_method', 'put'
  - Idea.viewbox_list.each do |vb|
    - if vb.shown
      = render partial: vb.partial_name, layout: 'builder_box', locals: {vb: vb}
  = submit_tag 'Save', class: 'btn btn-primary', id: 'object-save'

app/views/ideas/index.html.haml
= render partial: 'admin_add_button', locals: {button_text: t('idea.add_button'), button_target: new_idea_url}

= render partial: 'type__1_admin_template'
.row
  .col-xs-center-9
    .row#idea-list-container
= javascript_include_tag 'idea_list.js'

app/views/ideas/new.html.haml
= form_tag("/ideas", method: :post, multipart: true) do
  - Idea.viewbox_list.each do |vb|
    - if vb.shown
      = render partial: vb.partial_name, layout: 'builder_box', locals: {vb: vb}
  = submit_tag 'Save', class: 'btn btn-primary', id: 'object-save'

app/views/ideas/show.html.haml
%h1
  Idea #{@idea.title}
  %a{href: edit_idea_url(@idea)}
    %i.fa.fa-pencil.active-icon

.field
  .field-title
    Description
  .field-value
    #{@idea.description}