config/routes.rb
IdeaMapr::Application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  devise_for :admins, only: [:sessions, :passwords]
  
  resources :users, path: 'profiles'

  get '/public_info/double_bundle' => 'public_info#double_bundle'

  resources :respondents, only: [] do
    collection do
      get :reset
    end
  end
      
  resources :individual_answers, only: [:create, :update]
  resources :ideas
  resources :survey_questions
  resources :question_details, only: [:index, :create]

  resources :surveys do
    collection do
      post '/update', action: 'update'
      get '/public_show/:public_link', action: 'public_show', as: 'public_show'
    end
    member do
      get :report
    end
  end
  
  post '/ajax_api' => 'ajax#multiplex'
  get '/ajax_api' => 'ajax#multiplex'
  
  root to: 'ideas#index'

  # Adds RailsAdmin
  mount RailsAdmin::Engine => '/rails_admin', as: 'rails_admin'

  # Need a catch all to redirect to the errors controller, for catching 404s as an exception
  match "*path", to: "errors#catch_404", via: [:get, :post]
end

app/models/survey_question.rb
class SurveyQuestion < ActiveRecord::Base
  def question_type_enum
    (0..QuestionType.max_type).inject({}) do |acc, i|
      acc[QuestionType.name(i)] = i
      acc
    end
  end

  def self.viewbox_list
    unless Struct.const_defined? 'SurveyQuestionVbStruct'
      Struct.new('SurveyQuestionVbStruct', :partial_name, :title, :box_key, :expected_length, :help_text, :shown) do
        def initialize(*args)
          super
          self.shown = true
        end
      end
    end    
    l = [Struct::SurveyQuestionVbStruct.new('add_title', 'Question Title', 'sq-title', 1, 'Add a title for your survey'),
         Struct::SurveyQuestionVbStruct.new('add_question_type', 'Question Type', 'sq-question-type', -1, 'Types are either those that contain lists of ideas, or those that collect information from the participant'),
         Struct::SurveyQuestionVbStruct.new('question_prompt', 'Write An Explanation Prompt', 'sq-question-prompt', 1, 'The prompt is shown at the top of the survey question screen'),
         Struct::SurveyQuestionVbStruct.new('set_budget', 'Set Budget', 'sq-set-budget', -1, 'This is used in budget questions, as the maximum available spend'),
         Struct::SurveyQuestionVbStruct.new('add_ideas', 'Add Ideas', 'sq-add-ideas', -1, 'Select ideas and set ranked order'),
         Struct::SurveyQuestionVbStruct.new('new_idea_template', 'Question Preview', 'sq-new-idea', -1, ''),
         Struct::SurveyQuestionVbStruct.new('add_fields', 'Add Fields', 'sq-add-fields', -1, 'Select fields and set ranked order')]
    
    l
  end
  
  def self.valid_type?(id)
    id.to_i >= 0 and id.to_i <= QuestionType.max_type
  end
  class QuestionType
    PROCON=0
    RANKING=1
    NEW_IDEA=2
    BUDGETING=3
    TOPPRI=4
    RADIO_CHOICES=5
    TEXT_FIELDS=6
    
    def self.default_title(id)
      default_titles_array[id.to_i]
    end

    def self.max_type
      option_array.map { |i| i[1]}.sort.last
    end
    
    def self.prompts
      {0 => 'survey_question.helper_defaults.procon',
       1 => 'survey_question.helper_defaults.ranking',
       2 => 'survey_question.helper_defaults.new_idea',
       3 => 'survey_question.helper_defaults.budgeting',
       4 => 'survey_question.helper_defaults.pickone',
       5 => 'survey_question.helper_defaults.nonidea_radio',
       6 => 'survey_question.helper_defaults.nonidea_fields'
      }
    end
    
    def self.default_titles_array
      ['Pro/con question', 'Ranking question', 'Suggest an Idea', 'Budgeting question', 'Top priority question',
       'Single-choice radio buttons', 'Free-form text fields']
    end
    
    def self.option_array
      [['Pro/Con', PROCON], ['Ranking', RANKING], ['Suggest Idea', NEW_IDEA], ['Budgeting', BUDGETING], ['Top Priority', TOPPRI],
       ['Non-idea: Radio', RADIO_CHOICES], ['Non-idea: Fields', TEXT_FIELDS]]
    end
    def self.filename_array
      [['procon', PROCON], ['ranking', RANKING], ['newidea', NEW_IDEA], ['budgeting', BUDGETING], ['toppri', TOPPRI],
       ['radio', RADIO_CHOICES], ['fields', TEXT_FIELDS]]
    end

    def self.name(id)
      option_array.select { |i| i[1] == id }.first&.first
    end
    def self.name_as_filename(id)
      filename_array.select { |i| i[1] == id }.first&.first
    end
  end
  
  has_many :question_assignments, dependent: :destroy
  has_many :surveys, through: :question_assignments
  
  has_many :ideas, through: :idea_assignments
  has_many :idea_assignments, as: :groupable, inverse_of: :groupable, dependent: :destroy

  has_many :individual_answers
  has_one :question_detail
  
  validates :title, length: {minimum: 1}
  def question_type_name
    QuestionType.name(question_type)    
  end

  def response_length
    # Number of idea assignments or details
    if question_type == QuestionType::NEW_IDEA
      -1
    else
      idea_ct = idea_assignments.count
      details_length = question_detail&.details_list&.size || 0
      [idea_ct, details_length].max
    end
  end

  rails_admin do
    compact_show_view=false
    object_label_method do
      :title
    end
    list do
      field :title
      field :question_type do
        formatted_value do
          SurveyQuestion::QuestionType.name(value)
        end
      end
    end

    show do
      field :title
      field :question_type do
        formatted_value do
          SurveyQuestion::QuestionType.name(value)
        end
      end
    end
  end
end

app/controllers/survey_questions_controller.rb
class SurveyQuestionsController < ApplicationController
  include RelationalLogic
  before_action :set_menubar_variables
  before_action :set_public_survey_or_admin!
  before_action :params_check

  def show
  end
  
  def index
    rendered = false
    @questions = nil

    # @public_request is set in set_public_survey_or_admin!
    if @public_request && @survey&.published?
      @questions = SurveyQuestion.includes(:question_assignments).order('question_assignments.ordering asc').where(question_assignments: {survey_id: @survey.id}).
                   all
    else
      if @survey
        ids = @survey.question_assignments.order(ordering: :asc).pluck(:survey_question_id)
        assg_qns = SurveyQuestion.includes(:question_assignments).order('question_assignments.ordering asc').where(question_assignments: {survey_id: @survey.id})
        if ids.empty?
          assg_qns = []
          remg_qns = SurveyQuestion.all
        else
          remg_qns = SurveyQuestion.where('id not in (?)', ids).all
        end
      else
        assg_qns = []
        remg_qns = SurveyQuestion.order(created_at: :desc).all
      end
    end

    if @public_request
      payload = json_payload @questions
    else
      if !request.xhr?
        @questions = assg_qns + remg_qns
      else
        payload = json_payload(assg_qns, true) + json_payload(remg_qns, false)
      end
    end

    render (request.xhr? ? ({json: payload}) : 'index')
  end

  def new
    set_dropdown_options
    @level2_menu = :create_survey_question
  end
  
  def edit
    set_dropdown_options
    @level2_menu = :create_survey_question
    
    @qn_idea_assignments = @question.idea_assignments
  end

  def update
    if save_question
        redirect_to survey_questions_url
    else
      set_dropdown_options
      flash.now[:alert] = t(:resource_creation_failure, resource_name: 'Survey Question')
      if params[:action] == 'update'
        render :edit
      else
        render :new
      end
    end
  end
  alias :create :update
  
  def save_question
    set_dropdown_options

    attrs = params[:survey_question].permit(:title, :question_type, :question_prompt, :budget)
    @question.attributes= attrs

    if @question.question_prompt.to_s&.strip.blank?
      # No blank prompts allowed
      @question.question_prompt = I18n.t SurveyQuestion::QuestionType.prompts[@question.question_type]
    end

    if !@question.valid?
      return false
    end
    
    idea_ids = question_details = nil    
    # We either got ideas or fields for a survey question

    if params[:question_details] and (deets = JSON.parse(params[:question_details])).is_a?(Hash)
      deets_array = deets.with_indifferent_access[:details]
      
      # question_details should be an array of idea or detail attributes
      component_array = deets_array.sort_by { |i| i['component_rank']}
      
      if @question.question_type == SurveyQuestion::QuestionType::RADIO_CHOICES ||
         @question.question_type == SurveyQuestion::QuestionType::TEXT_FIELDS

        # the array of fields should be annotated with ids, so they can be consumed correctly
        # later when loaded in Backbone as a collection
        question_details = component_array.each_with_index.map do |item, idx|
          item['id'] = idx
          item
        end
      else 
        idea_ids = component_array.sort_by { |i| i['component_rank']}.map { |i|  i['id'] }
        idea_rev_index = component_array.inject({}) do |memo, hash|
          memo[hash['id']] = hash
          memo
        end
      end
    end    
    
    if (saved = @question.valid?)
      ActiveRecord::Base.transaction do      
        saved &= @question.save

        if idea_ids.present?
          update_has_many!(@question, 'Idea', 'IdeaAssignment', idea_ids, polymorphic: true, foreign_key: 'groupable_id',
                           should_delete: true)
          
          # For idea questions, that have budgets assigned...
          if @question.question_type == SurveyQuestion::QuestionType::BUDGETING
            new_assignments = @question.idea_assignments.all.to_a.map do |ia|
              if idea_rev_index.keys.include? ia.idea_id
                ia.budget = idea_rev_index[ia.idea_id]['budget'].to_f
              end

              ia
            end
            
            IdeaAssignment.import new_assignments,
                                  on_duplicate_key_update: { conflict_target: :id, columns: [:budget] }
          end
        elsif question_details.present?
          # There might be a record of Question Details already - delete it and refresh.
          if @question.question_detail.present?
            saved &= @question.question_detail.delete
          end

          # Backbone app will send the example fields as well that need to be filtered away here.
          clean_qd = question_details.reject {|i| /click to add/i.match(i['text'])}.
                     map do |detail|
            detail.delete 'response_data'
            detail
          end
            
          saved &= QuestionDetail.create survey_question: @question,
                                         details_list: clean_qd
        end
      end
    end

    # If the transaction didn't succeed, this will cause the caller function to appropriately bail to the browser.
    saved
  end

  private
  def set_menubar_variables
    @navbar_active_section = :survey_questions
  end
  
  def params_check
    status = true
    case params[:action]
    when 'new'
      @question = SurveyQuestion.new

      # For use in view helpers
      @form_object = @question
    when 'edit'
      status &= (params[:id] and (@question = SurveyQuestion.find_by_id(params[:id])))
      # For use in view helpers
      @form_object = @question
    when 'update', 'create'
      status &= (params[:action] == 'create' && params[:id].nil?) || (@question = SurveyQuestion.find_by_id(params[:id]))
      status &= !params[:survey_question].nil?
      if @question.nil?
        @question = SurveyQuestion.new
      end
    when 'show'
      status &= params[:id] and (@question = SurveyQuestion.find_by_id params[:id])
    when 'index'
      # We have already passed the public survey test which would have assigned @survey, and set the flag
      status &= @survey.present? || (params[:for_survey].blank? || (@survey = Survey.find_by_id(params[:for_survey])))
    end
    
    if !status
      redirect_to page_404
    end

    status
  end
  
  def set_dropdown_options
    @question_type_select = SurveyQuestion::QuestionType.option_array
    @select_default = @question.question_type || 1 # default for new = Ranking... TODO change it maybe?
  end

  def json_payload(qn_list, assigned = true)
    # Create a payload, mainly for Backbone app consumption, that allows display in multiple sections

    arr = []
    if qn_list.present?
      qn_list.inject(0) do |idx, qn|
        arr << {id: qn.id, title: qn.title, question_prompt: qn.question_prompt,
                question_type: qn.question_type,
                question_type_name: SurveyQuestion::QuestionType.name(qn.question_type),
                budget: qn.budget, component_rank: idx, is_assigned: assigned}
        idx += 1
      end
    end
    arr
  end
  
  def set_public_survey_or_admin!
    # Published surveys can have their questions revealed
    # if the survey's token is presented (via JSON)

    @public_request = false
    if params[:for_survey].nil?
      return authenticate_admin!
    end
    
    if request.xhr?
      s = Survey.find_by_public_link(params[:for_survey])
      if s&.status == Survey::SurveyStatus::PUBLISHED
        @survey = s
        return (@public_request = true)
      end

      # Look for it by id instead of public token
      if s.nil?
        s = Survey.find_by_id params[:for_survey]
      end
    else
      s = Survey.find_by_id(params[:for_survey]) || Survey.find_by_public_link(params[:for_survey])
    end
    
    # if the params[:for_survey] was set and survey still can't be found, it doesn't matter who's logged in
    # but if it is found, then we have to find someone logged in
    @survey = s    
    @survey.present? && authenticate_admin!
  end  
end

app/helpers/survey_questions_helper.rb
module SurveyQuestionsHelper
  def survey_question_show?(question_obj, vb)
    status = true
    # Don't show this box for new survey qns because budgeting is the not the default choice 
    if vb.box_key == 'sq-set-budget' &&
       (question_obj.id.nil? || question_obj.question_type != SurveyQuestion::QuestionType::BUDGETING)
      status = false
    end
    # Show this box for new survey qns because idea choices are defaults
    if vb.box_key == 'sq-add-ideas' &&
       question_obj.question_type.present? &&
       (question_obj.question_type == SurveyQuestion::QuestionType::RADIO_CHOICES ||
        question_obj.question_type == SurveyQuestion::QuestionType::TEXT_FIELDS)
      status = false
    end
    
    if vb.box_key == 'sq-add-fields' &&
       (question_obj.id.nil? or
        (question_obj.question_type != SurveyQuestion::QuestionType::RADIO_CHOICES &&
         question_obj.question_type != SurveyQuestion::QuestionType::TEXT_FIELDS))
      status = false
    end
    status
  end
  
  def show_conditional(form_obj, vb)
    form_obj.is_a?(SurveyQuestion) ? (survey_question_show?(form_obj, vb)) : true
  end
end

app/views/survey_questions/_add_fields.html.haml
#fields-list-app.row
= render 'survey_question_templates/all_field_templates'

app/views/survey_questions/_add_ideas.html.haml
#idea-list-app.row.relative-container
  #selected-list.col-xs-12
    .row
  #search-list.col-xs-12.unassigned-components

= render 'survey_question_templates/all_idea_templates'
    
%script#admin-add-idea-list{type: 'text/template'}
  .row
    %button.btn.btn-primary.with-text#add-component{type: 'button'}
      = t('buttons.survey_question.add_idea')

app/views/survey_questions/_add_question_type.html.haml
.row
  = select_tag('survey_question[question_type]', options_for_select(@question_type_select, @select_default))

app/views/survey_questions/_add_title.html.haml
.relative-container
  = text_field_tag 'survey_question[title]', @question.title, class: 'form-control validated-box', autofocus: true, 'data-expected-length' => vb.expected_length
  = label_tag 'survey_question[title]', t('prompts.survey_question.title'), class: 'placeholder-label'

app/views/survey_questions/_new_idea_template.html.haml
.col-xs-12.bottom-padding
  .bold-text.bottom-padding
    Title
  .fake-textfield
    Add a short title for your idea
.col-xs-12
  .bold-text.bottom-padding
    Description
  .fake-textarea
    Add a description  

app/views/survey_questions/_question_prompt.html.haml
.aligner
  = label_tag :question_prompt
  = text_area_tag 'survey_question[question_prompt]', @question.question_prompt
.helper-line
  Default is:
  %span#helper-edit

app/views/survey_questions/_set_budget.html.haml
= text_field_tag 'survey_question[budget]', @question.budget, class: 'form-control budget-box', autofocus: true

app/views/survey_questions/edit.html.haml
#debug-message
= form_tag("/survey_questions/#{@question.id || '0'}", method: :post, id: :survey_question_edit) do
  = hidden_field_tag '_method', 'put'        
  = hidden_field_tag :survey_question_id, (@question.id || 0)
  = hidden_field_tag :saved_question_type, (@question.id ? @question.question_type : '')

  - SurveyQuestion.viewbox_list.each do |vb|
    - unless vb.partial_name == 'add_question_type' || !vb.shown
      = render partial: vb.partial_name, layout: 'builder_box', locals: {vb: vb}
  = submit_tag 'Save', class: 'btn btn-primary', id: 'object-save'

app/views/survey_questions/index.html.haml
= render partial: 'admin_add_button', locals: {button_text: t('survey_question.add_button'), button_target: new_survey_question_url}
      
- if @questions.size > 0
  .row
    .entity-set  
      - @questions.each do |question|
        .col-xs-center-9.question-row.goto-edit{'data-goto-target' => edit_survey_question_path(question)}
          .row.question-data{'data-object-id' => question.id, 'data-object-type' => 'survey_question'}
            .x-box
              X
            .h2-font.col-xs-12.question-card-line
              = question.title
            .survey-status.col-xs-12.question-card-line
              = SurveyQuestion::QuestionType.name(question.question_type) || 'Not set'
            .question-prompt.col-xs-12.question-card-line
              = question.question_prompt

app/views/survey_questions/new.html.haml
= form_tag("/survey_questions", method: :post, id: :survey_question_new) do
  = hidden_field_tag :survey_question_id, (@question.id || 0)
  - SurveyQuestion.viewbox_list.each do |vb|
    = render partial: vb.partial_name, layout: 'builder_box', locals: {vb: vb}
  = submit_tag 'Save', class: 'btn btn-primary', id: 'object-save'

app/views/survey_questions/show.html.haml
%h1
  Question: #{@question.title}
  %a{href: edit_survey_question_url(@question)}
    %i.fa.fa-pencil.active-icon

.field
  .field-title
    Question Type
  .field-value
    #{SurveyQuestion::QuestionType.name(@question.question_type)}
  .field-title
    Question Prompt
  .field-value
    #{@question.question_prompt}
  - if @question.question_type_name == 'Budgeting'
    .field-title
      Question Budget
      .field-value
        = @question.budget
  - if @question.question_type == 1 || @question.question_type == 3
    .field-title
      Number of Ideas
    .field-value
      = @question.idea_assignments.count
  - if @question.question_type >= 5
    .field-title
      Choices
    .field-value
      = @question.question_detail.details_list.map {|rec| rec['text']}.join('; ')