config/routes.rb
IdeaMapr::Application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  devise_for :admins, only: [:sessions, :passwords]
  
  resources :users, path: 'profiles'

  get '/public_info/double_bundle' => 'public_info#double_bundle'

  resources :respondents, only: [] do
    collection do
      get :reset
    end
  end
      
  resources :individual_answers, only: [:create, :update]
  resources :ideas
  resources :survey_questions
  resources :question_details, only: [:index, :create]

  resources :surveys do
    collection do
      post '/update', action: 'update'
      get '/public_show/:public_link', action: 'public_show', as: 'public_show'
    end
    member do
      get :report
    end
  end
  
  post '/ajax_api' => 'ajax#multiplex'
  get '/ajax_api' => 'ajax#multiplex'
  
  root to: 'ideas#index'

  # Adds RailsAdmin
  mount RailsAdmin::Engine => '/rails_admin', as: 'rails_admin'

  # Need a catch all to redirect to the errors controller, for catching 404s as an exception
  match "*path", to: "errors#catch_404", via: [:get, :post]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action do
    # Quite a few things to do before the app starts...
    I18n.locale = set_locale
    @signed_in_header = current_admin ? 'signed-in' : ''
  end

  rescue_from ActionController::RoutingError do |exception|
    error_message = I18n.t(:message_404)
    redirect_to page_404
  end

  private
  def set_locale
    # 1. Let's make our app use the locale
    
    params[:locale] || I18n.default_locale
  end

  def go_to_root(message)
    redirect_to root_path, :alert => message
  end 

  def self.default_url_options(options={})
    { locale: I18n.locale }
  end

  def page_404
    '/404.html'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def is_active(selection_type)
    @navbar_active_section && @navbar_active_section == selection_type ? 'menu-selected' : ''
  end
end

app/views/application/_admin_add_button.html.haml
.row
  .col-xs-center-9.admin-add-button
    %a{href: button_target}
      .btn.btn-primary
        = button_text

app/views/application/_builder_box.html.haml
.builder-box.row{class: !show_conditional(@form_object, vb) ? 'myhidden' : ''}
  .hidden{'data-box-key' => vb.box_key}
  .col-xs-offset-4.col-xs-4
    .title
      = vb.title
  .help-text
  .col-xs-12
    = yield

app/views/application/_footer.html.haml
.footer
  .cityname
    = link_to ENV['CITY_NAME'], ENV['CITY_SITE_LINK']
  .subfooter.row
    .col-xs-12{style: 'padding: 0;'}
      .itembox#box1
        = link_to 'Terms and Conditions', t('general.tos_url')
    .col-xs-12{style: 'padding-left: 5px;'}
      .itembox#box2
        = link_to 'Privacy Policy', t('general.privacy_url')

app/views/application/_google_analytics.html.haml
:javascript
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  
  ga('create', '#{ENV['GOOGLE_ANALYTICS_KEY']}', 'auto');
  ga('send', 'pageview');

app/views/application/_idea_card.html.haml
- remove_bottom ||= false
.row.idea-card-row{class: remove_bottom ? 'remove-bottom-margin' : ''}
  .col-xs-12.cancel-padding
    .row.cancel-margins
      .idea-image
        %image{src: '<%- card_image_url %>'.html_safe}
      .idea-title
        <%- title %>
      .idea-description
        %span.editbox
          <%- description %>
        %span.summary.wrapper
          %span
            <%= desc_summary %>
        %span.full.wrapper
          %span
            <%= description_with_breaks %>
      .moreless-text{'data-switch-to' => 'full'}
        = t('idea.card_more')

    .idea-attachments
      .centered-cell.bold-text
        Attachments
      

app/views/application/_navigation.html.haml
.navtop
  .nav-right
    - if current_admin
      = link_to 'Sign Out', destroy_admin_session_path, :method => :delete
    - else
      = link_to 'Sign In', new_admin_session_path
  - if current_admin
    .brand-header{class: @signed_in_header}
      = t(:site_brand)
    
- if current_admin
  .row.primary-level
    .col-xs-10.col-xs-offset-1.col-lg-4.col-lg-offset-4
      .secondary-item-border.col-xs-4{class: is_active(:ideas)}
        .secondary-item
          = link_to t(:ideas), ideas_url
      .secondary-item-border.col-xs-4{class: is_active(:survey_questions)}
        .secondary-item
          = link_to t(:survey_questions), survey_questions_url
      .secondary-item-border.col-xs-4{class: is_active(:surveys)}
        .secondary-item
          = link_to t(:surveys), surveys_url

  - if @level2_menu
    .row.secondary-level
      .col-xs-8.col-xs-offset-2.col-lg-2.col-lg-offset-5.strike-padding
        .secondary-item
          %span.active-text
            = "#{t(@navbar_active_section)} >"
          %span.subsection-text
            = "#{t(@level2_menu)}"

app/views/application/_public_navigation.html.haml
.navtop
  .brand-header
    = @survey.title
    
    