config/routes.rb
IdeaMapr::Application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  devise_for :admins, only: [:sessions, :passwords]
  
  resources :users, path: 'profiles'

  get '/public_info/double_bundle' => 'public_info#double_bundle'

  resources :respondents, only: [] do
    collection do
      get :reset
    end
  end
      
  resources :individual_answers, only: [:create, :update]
  resources :ideas
  resources :survey_questions
  resources :question_details, only: [:index, :create]

  resources :surveys do
    collection do
      post '/update', action: 'update'
      get '/public_show/:public_link', action: 'public_show', as: 'public_show'
    end
    member do
      get :report
    end
  end
  
  post '/ajax_api' => 'ajax#multiplex'
  get '/ajax_api' => 'ajax#multiplex'
  
  root to: 'ideas#index'

  # Adds RailsAdmin
  mount RailsAdmin::Engine => '/rails_admin', as: 'rails_admin'

  # Need a catch all to redirect to the errors controller, for catching 404s as an exception
  match "*path", to: "errors#catch_404", via: [:get, :post]
end

app/views/layouts/application.html.haml
!!! html
%html
  %head
    %title #{@g_set_title || t(:site_title)}
    %meta{name: "viewport", content: "width=device-width, initial-scale=1.0"}
    /
      HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries
      WARNING: Respond.js doesn't work if you view the page via file://

    / [if lt IE 9]
      %script{src: "https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"}
      %script{src: "https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"}

    = stylesheet_link_tag    "application", media: "screen", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{Rails.application.secrets.google_maps_api_key}"
    = yield :extra_js
    = csrf_meta_tags

  %body
    = render "navigation"
    .container-fluid
      -if flash[:notice] or flash[:alert]
        .row
        -if flash[:notice]
          .alert.alert-info
            #{flash[:notice]}
        -if flash[:alert]
          .alert.alert-danger
            #{flash[:alert]}
      .main
        .overlay
        = yield
    = render 'footer'
  = render partial: 'google_analytics'

app/views/layouts/public_survey.html.haml
!!! html
%html
  %head
    %title #{@g_set_title || t(:site_title)}
    %meta{name: "viewport", content: "width=device-width, initial-scale=1.0"}
    /
      HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries
      WARNING: Respond.js doesn't work if you view the page via file://

    / [if lt IE 9]
      %script{src: "https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"}
      %script{src: "https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"}

    = stylesheet_link_tag    "application_public", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application_public", "data-turbolinks-track" => true
    = yield :extra_js
    = csrf_meta_tags

  %body
    = render "public_navigation"
    .container-fluid
      .main
        = yield
    = render 'footer'

  = render partial: 'google_analytics'

app/views/layouts/survey_report.html.haml
!!! html
%html
  %head
    %title #{@g_set_title || t(:site_title)}
    %meta{name: "viewport", content: "width=device-width, initial-scale=1.0"}
    /
      HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries
      WARNING: Respond.js doesn't work if you view the page via file://

    / [if lt IE 9]
      %script{src: "https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"}
      %script{src: "https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"}

    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = yield :extra_js
    = csrf_meta_tags

  %body
    .navtop{style: 'text-align: center;'}
      = succeed '&#8592;'.html_safe do
        = link_to @survey.title, edit_survey_path(@survey)
    .container-fluid
      .main
        = yield